src/main/java/br/com/bb/superto/model/Macro.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bb.superto.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 *
 * @author administrador
 */

@Entity
@Table(name = "macro")
public class Macro implements java.io.Serializable, GenericEntity{
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id; 

    private String Nome; 
    private String Relatorio; 
    @Column(columnDefinition = "TEXT")
    private String InstrucoesMacro; //Arquivo IIM?????
    private String Motivo; 
    private String URL;
    
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date dataCadastro; 
    private String ChaveSolicitante; 

    public Macro() {
    }

    public Macro(Integer id, String Nome, String Relatorio, String InstrucoesMacro, String Motivo, String URL, Date dataCadastro, String ChaveSolicitante) {
        this.id = id;
        this.Nome = Nome;
        this.Relatorio = Relatorio;
        this.InstrucoesMacro = InstrucoesMacro;
        this.Motivo = Motivo;
        this.URL = URL;
        this.dataCadastro = dataCadastro;
        this.ChaveSolicitante = ChaveSolicitante;
    }
    
    public Macro(String Nome, String Relatorio, String Motivo, Date dataCadastro, String ChaveSolicitante, String url) {
        this.Nome = Nome;
        this.Relatorio = Relatorio;
        this.Motivo = Motivo;
        this.dataCadastro = dataCadastro;
        this.ChaveSolicitante = ChaveSolicitante;
        this.URL = url;
    }

    public String getURL() {
        return URL;
    }

    public void setURL(String URL) {
        this.URL = URL;
    }
    
    @Override
    public Integer getId() {
        return id;
    }

    public String getMotivo() {
        return Motivo;
    }

    public void setMotivo(String Motivo) {
        this.Motivo = Motivo;
    }

    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getNome() {
        return Nome;
    }

    public void setNome(String Nome) {
        this.Nome = Nome;
    }

    public String getRelatorio() {
        return Relatorio;
    }

    public void setRelatorio(String Relatorio) {
        this.Relatorio = Relatorio;
    }

    public String getInstrucoesMacro() {
        return InstrucoesMacro;
    }

    public void setInstrucoesMacro(String InstrucoesMacro) {
        this.InstrucoesMacro = InstrucoesMacro;
    }

    public Date getDataCadastro() {
        return dataCadastro;
    }

    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }

    public String getChaveSolicitante() {
        return ChaveSolicitante;
    }

    public void setChaveSolicitante(String ChaveSolicitante) {
        this.ChaveSolicitante = ChaveSolicitante;
    }
    
    
}

src/main/java/br/com/bb/superto/model/Organograma.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bb.superto.model;

import javax.persistence.*;
import java.io.Serializable;

/**
 * @author maycon
 */
@Entity
@Table(name = "organograma")
public class Organograma implements Serializable, GenericEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    @ManyToOne
    private Funcionarios func;
    @ManyToOne
    private Organograma parent;

    @Override
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Funcionarios getFunc() {
        return func;
    }

    public void setFunc(Funcionarios func) {
        this.func = func;
    }

    public Organograma getParent() {
        return parent;
    }

    public void setParent(Organograma parent) {
        this.parent = parent;
    }

    @Override
    public String toString() {
        return "Organograma{" + "id=" + id + ", func=" + func + ", parent=" + parent + '}';
    }

}

src/main/java/br/com/bb/superto/controller/OrganogramaController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bb.superto.controller;

import br.com.bb.superto.dao.OrganogramaDao;
import br.com.bb.superto.model.Funcionarios;
import br.com.bb.superto.model.Organograma;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author maycon
 */
@ManagedBean(name = "organograma")
@ViewScoped
public class OrganogramaController extends GenericController<Organograma> implements java.io.Serializable {

    private Organograma superitendente;
    private Organograma parent;
    private Funcionarios funcionarioSelecionado;
    private Integer idParent;
    private Integer idOrganograma;
    private boolean opSucess;

    public OrganogramaController() {
        superitendente = new OrganogramaDao().getList().get(0);
        opSucess = false;
    }

    public void delete(Integer id) {
        new OrganogramaDao().deletePorId(id);
    }

    public void add2() {
        parent = new OrganogramaDao().getPorId(idParent).get(0);
        System.out.println("testando");
        System.out.println(funcionarioSelecionado.getId());
        System.out.println(parent.getId());
        value = new Organograma();
        value.setFunc(funcionarioSelecionado);
        value.setParent(parent);
        value.setId(Integer.SIZE);
        new OrganogramaDao().save(value);
    }

    public List<Organograma> getGerentes() {
        return new OrganogramaDao().getChildrens(superitendente);
    }

    public Organograma getSuperitendente() {
        return superitendente;
    }

    public void setSuperitendente(Organograma superitendente) {
        this.superitendente = superitendente;
    }

    public List<Organograma> getChildrens(Integer id) {
        return new OrganogramaDao().getChildrens(id);
    }

    public Organograma getParent() {
        return parent;
    }

    public void setParent(Organograma parent) {
        this.parent = parent;
    }

    public Funcionarios getFuncionarioSelecionado() {
        return funcionarioSelecionado;
    }

    public void setFuncionarioSelecionado(Funcionarios funcionarioSelecionado) {
        this.funcionarioSelecionado = funcionarioSelecionado;
    }

    public Integer getIdParent() {
        return idParent;
    }

    public void setIdParent(Integer idParent) {
        this.idParent = idParent;
    }

    public Integer getIdOrganograma() {
        return idOrganograma;
    }

    public void setIdOrganograma(Integer idOrganograma) {
        this.idOrganograma = idOrganograma;
    }

    public boolean isOpSucess() {
        return opSucess;
    }

    public void setOpSucess(boolean opSucess) {
        this.opSucess = opSucess;
    }

    @Override
    public void add() {
        try {
            value = new Organograma();
            value.setFunc(funcionarioSelecionado);
            value.setParent(superitendente);
            value.setId(Integer.SIZE);
            opSucess = new OrganogramaDao().save(value) != null;
        } catch (Exception ex) {
            Logger.getLogger(OrganogramaController.class.getName()).log(Level.SEVERE, "Erro ao salvar arquivo!", ex);
        }

    }

    @Override
    public void edit() {
        try {
            parent.setFunc(funcionarioSelecionado);
            opSucess = new OrganogramaDao().makePersistent(parent) != null;
        } catch (Exception ex) {
            Logger.getLogger(OrganogramaController.class.getName()).log(Level.SEVERE, "Erro ao editar arquivo!", ex);
        }

    }

    @Override
    public void delete() {
    }
}

src/main/webapp/admin/organograma/editarorganograma.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                template="./../../resources/templates/admTemplate_bootStrap.xhtml"
                xmlns:f="http://java.sun.com/jsf/core">

    <ui:define name="title">
        Intranet Administração - Editar Organograma
    </ui:define>

    <ui:define name="content">
        <fieldset>
            <legend><h2>Editar Organograma</h2></legend>

            <h:form id="add" prependId="false" style="font-size: 11px;">
                <p:dialog id="adicionar" widgetVar="adicionarDlg" header="Selecionar Funcionario" showEffect="clip"
                          hideEffect="clip"
                          resizable="false" modal="true" dynamic="true" style="font-size: 11px;">
                    <h:panelGrid columns="1">
                        <h:outputText value="Funcionario" style="font-size: 11px;"/>
                        <p:selectOneMenu value="#{organograma.funcionarioSelecionado}" filter="true" var="p"
                                         converter="baseEntityConverter">
                            <f:selectItem itemLabel="Select One" itemValue=""/>
                            <f:selectItems value="#{funcController.funcs}" var="player"
                                           itemLabel="#{player.nome}" itemValue="#{player}"/>
                            <p:column style="font-size: 11px;">
                                #{p.fmatricula}
                            </p:column>
                            <p:column style="font-size: 11px;">
                                #{p.nome}
                            </p:column>
                        </p:selectOneMenu>
                        <hr style="border: none; border-bottom: 1px solid rgb(221, 221, 221); "/>
                        <p:commandButton value="Adicionar"
                                         update=":form2:tab1:noticias2 :form2:tab1:n :form2:noticias adicionar"
                                         actionListener="#{organograma.add()}" style="font-size: 11px;"/>
                    </h:panelGrid>
                </p:dialog>
            </h:form>

            <h:form id="aditarForm" prependId="false" style="font-size: 11px;">
                <p:dialog id="editar" widgetVar="editarDlg" header="Selecionar Funcionario" showEffect="clip"
                          hideEffect="clip"
                          resizable="false" modal="true" dynamic="true">
                    <h:panelGrid columns="1">
                        <h:outputText value="Funcionario" style="font-size: 11px;"/>
                        <p:selectOneMenu value="#{organograma.funcionarioSelecionado}" filter="true" var="p"
                                         converter="baseEntityConverter">
                            <f:selectItem itemLabel="Select One" itemValue=""/>
                            <f:selectItems value="#{funcController.funcs}" var="player"
                                           itemLabel="#{player.nome}" itemValue="#{player}"/>
                            <p:column style="font-size: 11px;">
                                #{p.fmatricula}
                            </p:column>
                            <p:column style="font-size: 11px;">
                                #{p.nome}
                            </p:column>
                        </p:selectOneMenu>
                        <hr style="border: none; border-bottom: 1px solid rgb(221, 221, 221); "/>
                        <p:commandButton value="Alterar" update=":form2:tab1:noticias2 :form2:tab1:n"
                                         actionListener="#{organograma.edit()}" style="font-size: 11px;"
                                         oncomplete="PF('editarDlg').hide();"/>
                    </h:panelGrid>
                </p:dialog>
            </h:form>

            <h:form id="add2" prependId="false" style="font-size: 11px;">
                <p:dialog id="adicionar2" widgetVar="adicionarDlg2" header="Selecionar Funcionario" showEffect="clip"
                          hideEffect="clip"
                          resizable="false" modal="true">
                    <h:panelGrid columns="1">
                        <h:outputText value="Gerente/Superintendete Regional"/>
                        <p:selectOneMenu value="#{organograma.idParent}" style="font-size: 11px;">
                            <f:selectItem itemLabel="Select One" itemValue=""/>
                            <f:selectItems value="#{organograma.gerentes}" var="player"
                                           itemLabel="#{player.func.nome}" itemValue="#{player.id}"/>
                        </p:selectOneMenu>
                        <h:outputText value="Funcionario" style="font-size: 11px;"/>
                        <p:selectOneMenu value="#{organograma.funcionarioSelecionado}" filter="true" var="p"
                                         converter="baseEntityConverter">
                            <f:selectItem itemLabel="Select One" itemValue=""/>
                            <f:selectItems value="#{funcController.funcs}" var="player"
                                           itemLabel="#{player.nome}" itemValue="#{player}"/>
                            <p:column style="font-size: 11px;">
                                #{p.fmatricula}
                            </p:column>
                            <p:column style="font-size: 11px;">
                                #{p.nome}
                            </p:column>
                        </p:selectOneMenu>
                        <hr style="border: none; border-bottom: 1px solid rgb(221, 221, 221); "/>
                        <p:commandButton value="Adicionar" update=":form2:tab1:n adicionar2 :form2:noticias"
                                         actionListener="#{organograma.add2()}" style="font-size: 11px;"/>
                    </h:panelGrid>
                </p:dialog>
            </h:form>

            <h:form id="form2" prependId="false">
                <div style="padding-left: 28px; width: 300px;">
                    <p:messages id="noticias"/>
                </div>

                <h2>Superintendente - Edvaldo Sebastião</h2>
                <br/>

                <div style="width: 400px;">

                    <p:tabView id="tab1">

                        <p:tab title="Gerentes">
                            <p:commandButton value="Adicionar" icon="ui-icon-disk" style="font-size: 11px;"
                                             onclick="PF('adicionarDlg').show();" type="button"/>
                            <p:dataTable id="noticias2" var="noticia" value="#{organograma.gerentes}"
                                         emptyMessage="Não foi encontrado nenhum resultado"
                                         selectionMode="single" selection="#{organograma.selected}"
                                         rowKey="#{noticia.id}" rows="10" style="font-size: 11px;">
                                <ui:remove>
                                    <p:ajax event="rowSelect" update=":form:confirmDialog"/>
                                </ui:remove>

                                <p:column headerText="FMatricula" style="font-size: 11px;">
                                    #{noticia.func.fmatricula}
                                </p:column>
                                <p:column headerText="Nome" style="font-size: 11px;">
                                    #{noticia.func.nome}
                                </p:column>
                                <p:column headerText="Opções" style="font-size: 11px;">
                                    <div style="text-align: center;">
                                        <p:commandLink ajax="true" oncomplete="PF('editarDlg').show();">
                                            <img src="pencil.png" alt="Editar"/>
                                            <f:setPropertyActionListener target="#{organograma.funcionarioSelecionado}"
                                                                         value="#{noticia.func}"/>
                                            <f:setPropertyActionListener target="#{organograma.parent}"
                                                                         value="#{noticia}"/>
                                        </p:commandLink>
                                        <p:commandLink actionListener="#{organograma.delete(noticia.id)}"
                                                       update=":form2:tab1:noticias2">
                                            <img src="cross.png" alt="Deletar"/>
                                        </p:commandLink>
                                    </div>
                                </p:column>
                            </p:dataTable>

                        </p:tab>

                        <p:tab title="Analistas/Outros">
                            <p:commandButton value="Adicionar" icon="ui-icon-disk" style="font-size: 11px;"
                                             onclick="PF('adicionarDlg2').show();" type="button"/>
                            <p:dataTable id="n" var="noticia2" value="#{organograma.gerentes}"
                                         emptyMessage="Não foi encontrado nenhum resultado"
                                         selectionMode="single" selection="#{organograma.selected}"
                                         rowKey="#{noticia2.id}" rows="10" style="font-size: 11px;"
                                    >
                                <f:facet name="header">
                                    Analistas
                                </f:facet>
                                <p:columnGroup type="header">
                                    <p:row>
                                        <p:column rowspan="2" headerText="Nome" sortBy="#{noticia2.func.nome}"
                                                  style="font-size: 11px;"/>
                                        <p:column colspan="2" headerText="Analistas/Outros" style="font-size: 11px;"/>
                                    </p:row>
                                    <p:row>
                                        <p:column headerText="FMatricula" style="font-size: 11px;"/>
                                        <p:column headerText="Opções" style="font-size: 11px;"/>
                                    </p:row>
                                </p:columnGroup>
                                <p:subTable var="stats" value="#{organograma.getChildrens(noticia2.id)}">
                                    <f:facet name="header">
                                        <h:outputText style="font-size: 12px;" value="#{noticia2.func.nome}"/>
                                    </f:facet>
                                    <p:column style="font-size: 11px;">
                                        #{stats.func.nome}
                                    </p:column>
                                    <p:column style="font-size: 11px;">
                                        #{stats.func.fmatricula}
                                    </p:column>
                                    <p:column style="font-size: 11px;">
                                        <div style="text-align: center;">
                                            <p:commandLink ajax="true" oncomplete="PF('editarDlg').show();">
                                                <img src="pencil.png" alt="Editar"/>
                                                <f:setPropertyActionListener
                                                        target="#{organograma.funcionarioSelecionado}"
                                                        value="#{stats.func}"/>
                                                <f:setPropertyActionListener target="#{organograma.parent}"
                                                                             value="#{stats}"/>
                                            </p:commandLink>
                                            <p:commandLink actionListener="#{organograma.delete(stats.id)}"
                                                           update=":form2:tab1:n">
                                                <img src="cross.png" alt="Deletar"/>
                                            </p:commandLink>
                                        </div>
                                    </p:column>
                                </p:subTable>
                            </p:dataTable>
                        </p:tab>
                    </p:tabView>
                </div>
            </h:form>
        </fieldset>
    </ui:define>
</ui:composition>